CREATE OR REPLACE FUNCTION obter_descricao_segmercado
(p_ID IN SEGMERCADO.ID%type)
RETURN SEGMERCADO.DESCRICAO%type
IS
  v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN
  SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = p_ID;
  RETURN v_DESCRICAO;
END;


DECLARE
   v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN
    v_DESCRICAO := obter_descricao_segmercado(2);
    dbms_output.put_line('A Descri��o do Segmento de Mercado � ' || v_DESCRICAO);
END;