INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (1, 'Varejo');

-- usando PLSQL:

DECLARE
   v_ID NUMBER(5) := 2;
   v_DESCRICAO VARCHAR2(100) := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO);
   COMMIT;
END;

