CREATE OR REPLACE PROCEDURE INCLUIR_SEGMERCADO
(p_ID IN SEGMERCADO.ID%type, p_DESCRICAO IN SEGMERCADO.DESCRICAO%type)
IS
BEGIN
 INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, upper(p_DESCRICAO));
 COMMIT;
END;

EXECUTE INCLUIR_SEGMERCADO(3, 'Farmaceuticos');