INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (1, 'Varejo');

INSERT INTO CLIENTE (ID, RAZAO_SOCIAL, CNPJ, SEGMERCADO_ID, DATA_INCLUSAO, FATURAMENTO_PREVISTO, CATEGORIA)
   VALUES (1, 'SUPERMRECADO IJK', '67890000170', 1, sysdate, 1, 90000);